language: python
python:
  - "3.7"
before_script:
  - git clone https://github.com/myxie/shadow ~/shadow 
  - export PYTHONPATH=$PYTHONPATH:~/shadow/
  - chmod 0555 topsim/test/data/output

script: coverage run -m unittest discover test
after_script: coveralls


