language: python

before_script:
  - git clone https://github.com/myxie/shadow ~/shadow 
  - export PYTHONPATH=$PYTHONPATH:~/shadow/

script: coverage run topsim.py test --all
after_script: coveralls


