language: python

before_script:
  - git clone https://github.com/myxie/shadow ~/shadow 
  - export PYTHONPATH=$PYTHONPATH:~/shadow/

script: coverage run - unittest discover test
after_script: coveralls


