language: python

before_script:
  - git clone https://github.com/myxie/shadow ~/shadow 
  - export PYTHONPATH=$PYTHONPATH:~/shadow/

script: coverage run -m unittest test.test_planner
after_script: coveralls


